
---
AWSTemplateFormatVersion: '2010-09-09'
# Sample CFN YAML to demonstrate creating a connection
#
# Parameters section contains names that are substituted in the Resources section
# These parameters are the names the resources created in the Data Catalog
Parameters:
# The name of the connection to be created
  CFNConnectionName:
    Type: String
    Default: newishan
  CFNJDBCString:
    Type: String
    Default: "jdbc:postgresql://postgres.xxx.us-west-2.rds.amazonaws.com:5432/test"
  CFNJDBCUser:
    Type: String
    Default: "postgres"
  CFNJDBCPassword:
    Type: String
    Default: '{{resolve:secretsmanager:rdspwd:SecretString:password}}'
    NoEcho: true
#
# Resources section defines metadata for the Data Catalog
Resources:
   CFNConnectionMySQL:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: "Connect to MySQL database."
        ConnectionType: "JDBC"
        #MatchCriteria: none
        PhysicalConnectionRequirements:
          AvailabilityZone: "us-west-2d"
          SecurityGroupIdList:
           - "sg-xxx"
          SubnetId: "subnet-xxxx"
        ConnectionProperties: {
          "JDBC_CONNECTION_URL": !Ref CFNJDBCString,
          "USERNAME": !Ref CFNJDBCUser,
          "PASSWORD": !Ref CFNJDBCPassword
        }
        Name: !Ref CFNConnectionName
